### ISSUE TITLE
angular mape imena

### ISSUE THREAD

**Issue by sysmat** [aldingithub/blog-dev#5]
- ponekod so angleška imena ponekod slovenska
- [x] poenoti imena vsa na angleška(komponente -> components)
- [x] **class** mapa ni najbolj primerna, raje uporabimo **models**
- [x] on **arnes_review** branch

**Comment by sysmat** [comment]
- SHRAMBA_BRSKALNIKA bi bolje ustrezalo v kak **const.ts**
- ExchangeService ima **blog** objekt in potem **setBlog** uporabi **any**, bolje bi bilo imeti **class|type|interface** definicijo in v mapi models

```typescript
export interface Blog {
  id?: number;
 text: string;
 title: string;
 created: Date;
}
// ali preko type
export type Blog = {
    id?: number;
    text: string;
    title: string;
    created: Date;
}
// ali preko class
export class Blog {
    id?: number;
    text: string;
    title: string;
    created: Date;
   
    constructor() {
      this.created = new Date();
    }       
}
```

**Comment by sysmat** [comment]
- se naredi class-e v models mapi
```javascript
comment = {
    "id":"",
    "text":"",
    "creator":"",
    "main":"",
    "liked":0,
    "disliked":0
  }

nev = {
        "id": a,
        "tip":this.comment.id,
        "text": this.sadrzaj,
        "creator": res.username,
        "created": danas,
        "main":this.comment.main,
        "liked":0,
        "disliked":0
      };
```

**Comment by sysmat** [comment]
Kar ti je Klemen dal da so stvari poenotene po celem angular projekt(enojni | dvojni narekovaji, podpičja), v model že ni vredu

**Comment by sysmat** [comment]
properties v objektu ne rabijo narekovajev

**Comment by kle-pra** [comment]
Ja, tole sem naknadno opazil, dobra praksa je da se property-ji v objektih brez narekovajev uporabijo.

**Comment by sysmat** [comment]
pri model mi je ločevanje  prop z podpičjem boljše
